---
install: 
  - sudo apt-get install -y -qq -oDpkg::Use-Pty=0 texlive texlive-latex-extra cmake g++ poppler-utils latex2html
  - mktexlsr

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
