name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Install Nix
        uses: cachix/install-nix-action@v16
        with:
          nix_path: 'nixpkgs=./nix'

      - name: Install niv
        uses: cachix/cachix-action@v10
        with:
          name: niv

      - name: Build LaTeX
        run: nix-shell --run make

      - name: Upload Resume
        uses: actions/upload-artifact@v3
        if: github.ref == 'refs/heads/master'
        with:
          name: eric-crosson-resume
          path: Eric_Crosson_Resume.pdf

  upload:

    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs:
      - build

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Download Resume
        uses: actions/download-artifact@v3
        with:
          name: eric-crosson-resume

      - name: Checkout deliverables branch
        run: git checkout deliverables || git checkout --orphan deliverables

      - name: Publish Resume
        uses: EndBug/add-and-commit@v9
        with:
          add: Eric_Crosson_Resume.pdf
          default_author: github_actions
          push: origin deliverables --set-upstream --force
