---
name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v8

      - name: Build LaTeX
        run: nix build

      # The upload-artifact action errors when the upload path includes a symlink;
      # the workaround is to resolve the symlink before invoking upload_path.
      # https://github.com/actions/upload-artifact/issues/92#issuecomment-1080347032
      - name: Prepare Upload
        if: github.ref == 'refs/heads/master'
        run: echo "UPLOAD_PATH=$(readlink -f result/Eric_Crosson_Resume.pdf)" >> "$GITHUB_ENV"

      - name: Upload Resume
        uses: actions/upload-artifact@v4
        if: github.ref == 'refs/heads/master'
        with:
          name: eric-crosson-resume
          path: ${{ env.UPLOAD_PATH }}

  upload:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs:
      - build

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: deliverables

      - name: Download Resume
        uses: actions/download-artifact@v3
        with:
          name: eric-crosson-resume

      - name: Publish Resume
        uses: EndBug/add-and-commit@v9
        with:
          add: Eric_Crosson_Resume.pdf
          default_author: github_actions
          push: origin deliverables --set-upstream --force
